### ISSUE TITLE
Offset does not seem to be working

### ISSUE THREAD

**Issue by JesseAbram** [sbruno81/rets-client#126]
Package version 
5.2.3

RETS version 
1.7 (the Toronto one, seems to have a lot of issues dedicated to it)

Problem 
We are trying to pull the whole RETS database into our own database to limit our query's on the RETS server. Therefore we are trying to loop through the requests incrementing our offset by our limit amount so we can pull the whole database into ours while limiting the size of our queries. When we use offset, no matter what value we pass through we start from the same entry each time 

Code sample 
` var streamResult = client.search.stream.query( 'Property', 'ResidentialProperty', '(status=A)', { limit: 100, offset: offset } )
`

**Comment by zacronos** [comment]
I've seen this before -- it is most likely not a problem with rets-client, it is that your RETS server is configured to ignore the offset parameter.  Usually, this is a business choice because they specifically want to prevent folks from pulling the entire database, as you are trying to do.

I suggest you reach out to your technical contact for the RETS server, and discuss the issue with them.  They might be able to make an exception for your account, if you can convince them to do so.

**Comment by esvinson** [comment]
Yeah, most likely the RETS server doesn't allow the use of offset.  I'd recommend trying to accomplish what you're trying to do by pulling back just the ID values from your normal query, and then do queries on large subsets of those IDs. (500+ at a time if it supports it)
