### ISSUE TITLE
Nothing returned to console

### ISSUE THREAD

**Issue by lance0821** [sbruno81/rets-client#22]
When executing any of the examples, nothing is returned back to the console. I would expect to get credential errors or some sort of console log but I am just greeted with the command prompt again. Any help on troubleshooting this problem would be appreciated. I am using node 5.6.0 and npm 3.7.2. Do I need to possibly downgrade my versions? I also forgot to add I know my RETS server is looking for POST request instead of GET. Could this also be the issue?

**Comment by zacronos** [comment]
That is strange.  I generally use node 4.x and npm 2.x, but I just tested with your versions and confirmed the problem does not exist.  (I did, however, find a couple typos in the example code, and have fixed them in latest/v4.0.4.)

It sounds like you're pasting code into the terminal.  Are you returned to the actual command prompt (which generally looks like `> `) or do you get the 'waiting for more input' prompt (which generally looks like `... `)?  I often find node does not work well when pasting more than a line or two at once.  It is generally better to put code into a file, and then run e.g. `node sample_code.js` rather than pasting code into the terminal.

If the above doesn't help, try setting the DEBUG environment variable to `rets-client:*`, and see if you get any logging that way.

**Comment by lance0821** [comment]
I did have my code in a file and executed it with node sample code.js. I cut and pasted the code from the readme, should I cut and paste from another source? Thanks again

**Comment by zacronos** [comment]
That's correct, but I did make a couple changes to the example code in the readme after you opened this issue.  Are you still having the same problem?  If so, please try again after setting DEBUG to `rets-client:*` and let me know what happens.

**Comment by lance0821** [comment]
Ok thanks I will check it out when I get home and report back

**Comment by lance0821** [comment]
GET vs POST will not cause errors? With Trulia RETS client, libRETS, and PHRETs I have to configure my library to use POST. Is this necessary with rets-client?

**Comment by lance0821** [comment]
ok it looks like the fixed code in the README works now, thanks a lot!

**Comment by lance0821** [comment]
After checking the examples and issuing a query for a property I am greeted with a 404 error, I have looked at the DMQL string in debug and compared it to the one used for Openhouse (Which works fine), I have double checked my fields and suitable values for a query and everything looks fine, it is using a GET request and I think I need it to use a POST request for my Listing class, how can I configure this?

**Comment by zacronos** [comment]
Hmm.  There is currently no way to configure that.

I'll take a look at the RETS standard and see if it says when to use GET versus POST.  If it does, I should be able to change the code behind the scenes to do this properly.  If it doesn't (and it is a server-specific requirement), then I'll have to add a feature to allow selecting the method as an option.  I'll try to get to this soon.

**Comment by lance0821** [comment]
Could I add the parameter method: 'POST' to the request in the base code? If so where would I add this just to verify its my issue?

**Comment by zacronos** [comment]
I think you could change all requests to use POST instead of GET by changing lines 25-27 of retsHttp.js to:
```javascript
return retsSession.post({
   form: queryOptions
});
```

But since that's in a helper function used for all requests, I'm not sure a simple change there will work -- that would change all requests to POST, and since some of your queries worked fine (login, Openhouse, maybe some others) they might need to stay with GET.

Even to test whether that's the problem, you'll probably need to add an option so you can specify whether to use the POST code above or the existing:
```javascript
return retsSession({
   qs: queryOptions
});
```

**Comment by lance0821** [comment]
Ok thanks I'll give it a try. I think all my queries will work with POST. With other libraries I've configured them to use POST and had no issues.

**Comment by zacronos** [comment]
Great, let me know the results.

**Comment by lance0821** [comment]
Do you have any resources I can look over to implement this library, requesting certain fields, and how to utilize the streams? I'm not a Nodejs or Javascript guru but this seems like the best library for my purposes I have tried so far.

Thanks for the help I was able to get rets-client to submit post requests by modifying lines 67-71 of client.js to look like this
```javascript
      defaults = {
        jar: request.jar(),
        headers: this.headers,
        method: 'POST'
      };

**Comment by zacronos** [comment]
Ok, thanks for the info, it has been very helpful.

The RETS standard seems to say both GET and POST should be fine, except for update actions which are not possible with rets-client anyway.  So, this seems to be yet another case of "some servers just don't obey the standards".  :-/

Based on your results, I've added a client setting to allow specifying the method (v4.1.0 release).  For backwards compatibility, I'm leaving GET as the default.

As for resources, other than the example code in the README, sorry, no there isn't anything available.  Maybe someday -- I'd be happy to merge any PRs that do improve the documentation.
