### ISSUE TITLE
Unable to get any Search queries

### ISSUE THREAD

**Issue by Xtremehead** [sbruno81/rets-client#37]
I've successfully been able to log into the RETS server through code, but I'm unable to get any search queries to work even though I'm passing what looks to be the only required field Status. It always returns with:

Required search fields missing. Reference ID: 32d76453-0bdf-43af-8f84-0550ed24dff2

Am I doing anything wrong? ( I'm testing out the endpoint in C#)
https://gist.github.com/lynx44/15122fce65c377f01a433a4d91727a47

From the documentation I've read, it seems like this should work. I've tried all different combinations of search filters (always including Status), but I can never get past this error.

-Matt

**Comment by zacronos** [comment]
After looking at that gist, I'm not sure what is going on.  Are you using `rets-client` under the hood somehow?

Every RETS server is different and has different rules, so it's really hard to say, especially since I can't see any code that references `rets-client`.  If there is a bug in how you are using `rets-client`, for example, there's no way for me to spot it.

Since you have a Reference ID, your best bet is probably to reach out to the technical support contact for that RETS system and ask them what was wrong with the query associated with that ID.

**Comment by esvinson** [comment]
If I remember properly sefrets needed a | (pipe) before the options for a lookup field.
(246=|A,B,C,CS,PS,Q,T,W,X)
