### ISSUE TITLE
client.search.query without passing resource or class.

### ISSUE THREAD

**Issue by ranleung** [sbruno81/rets-client#40]
Hi,

I am using RetsConnector to query city and status (Status=|A),(City=|Pasadena) and is able to successfully get data back.  

![retsconnector_example](https://cloud.githubusercontent.com/assets/5177175/16248048/b5baae8c-37c1-11e6-9811-34cd4aeedc42.png)

However, when I am using 
```
return client.search.query("", "", "(Status=|A),(City=|Pasadena)", {limit:1, offset:0})
```
I am getting an undefined error.  Is there a way to omit resource and class parameter?

Thanks

**Comment by zacronos** [comment]
I don't know how that would work.  It is possible RetsConnector is using the "Property" resource by default since it is a well-known name, but I'm not sure how a suitable class could be chosen by default.  I suggest you inspect the resources and classes available via your RETS and use those values, rather than passing blank values.
