### ISSUE TITLE
cloning RETS DB

### ISSUE THREAD

**Issue by josephbisaillon** [sbruno81/rets-client#44]
I'm wondering what method you use to download the entire RETS database that you are accessing. I want to create an initial clone copy that I can just scan for changes on after I clone it. The issue is that overflowing memory while trying. I'm just interested to hear if you have an established method of doing this? Or any suggestions from anyone?

**Comment by zacronos** [comment]
Are you using the streaming methods?  Memory efficiency is the big plus for them.  App code is more complicated to write that way, but there's no way around the fact that if you load all the data into memory at once, you're going to have to use a lot of RAM.

**Comment by josephbisaillon** [comment]
Oh no, I'm a dummy, I didn't even see the streaming example. At a glance that is probably the proper solution for me! I'll give that a try tomorrow, thanks for the suggestion!

**Comment by josephbisaillon** [comment]
I seem to still be getting the "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory" even when using the example code. 

The only thing different that I did was use the ES6 Promises instead of bluebird. Any ideas?

**Comment by zacronos** [comment]
Are you also just using the example `doAsyncProcessing()`, or did you add in some of your own code at that step?  If you do anything that keeps references to the data or in any way builds up the data in memory rather than handling it as it flows through the stream and then forgetting about it, you will wind up with memory problems.  If you're confident you're not doing that...  then I'm not sure what to suggest.  It's not easy, but you may have to start trying to figure out what is building up in memory: http://www.nearform.com/nodecrunch/self-detect-memory-leak-node/

Although I don't think it would make a difference in this case, in general you might want to be in the habit of using bluebird rather than ES6 Promises: http://programmers.stackexchange.com/questions/278778/why-are-native-es6-promises-slower-and-more-memory-intensive-than-bluebird

**Comment by josephbisaillon** [comment]
I'll do some additional troubleshooting tonight. I'm starting to have a feeling it might be related to Mongoose which I am saving each piece of data with.

**Comment by josephbisaillon** [comment]
The root of the issue is actually in mongoose, closing this issue out.

**Comment by ranleung** [comment]
@josephbisaillon is there an email I can contact you at?  I am in a similar state and would grateful if I can chat with you about it.  Thanks

**Comment by josephbisaillon** [comment]
@ranleung sure thing my email is bisaillonjd@gmail.com go ahead and shoot me a message.

 If you are looking to download a large set of data and not get the memory error. I found using the native mongodb npm library and just saving the data immediately without any string manipulation works. I created a new Issue about slower operations causing the memory issue.
