### ISSUE TITLE
tough-cookie 0.13.0 and punycode 2.X

### ISSUE THREAD

**Issue by nmccready** [sbruno81/rets-client#63]
punycode 2.X technically requires node >= 6.X . npm lets you slide on this restriction however yarn does not. Should a different version of tough-cookie be used?

@zacronos

**Comment by nmccready** [comment]
Lastly it seems since tough-cookie hit version 1.1.0 it removed punycode as a dependency.

https://github.com/salesforce/tough-cookie/tree/v1.1.0

**Comment by nmccready** [comment]
I also do not see tough-cookie being used anywhere. However, there are no specs there fore I get no warm fuzzy when I remove it.

**Comment by nmccready** [comment]
https://github.com/sbruno81/rets-client/pull/64

**Comment by zacronos** [comment]
It looks like the dependency can be removed.

As for specs, it is actually very difficult to create specs for this library since any meaningful activity requires RETS server creds.  If an open test server were available, then specs could be written which use that server, but otherwise, so much would have to be mocked that the specs would be almost 100% useless.  The only test RETS server I've ever seen (which wasn't even a public test server) gave randomly generated responses to any request -- sometimes one of a number of possible errors, other times different sets of data.  This sort of test server is also extremely hard to write specs for.

I'm open to suggestions/PRs if anyone can think of a good way to handle this.

**Comment by nmccready** [comment]
It is not possible to set up a mock http server that returns mock responses?

**Comment by zacronos** [comment]
Accurately mocking the RETS spec and real RETS server behavior (which sometimes includes mistakes such that they don't follow the actual HTTP spec: see https://github.com/sbruno81/rets-client/issues/9#issuecomment-164558381) would be a really big undertaking, especially considering the desire to support multiple versions of the RETS standard and how so many places in the RETS standard say things like "the server MAY ...".

If there is a mock RETS server implementation out there which we could pull in and use with little effort, that would be great.
