### ISSUE TITLE
Offset when doing consecutive search.query() is not working properly?

### ISSUE THREAD

**Issue by GifCo** [sbruno81/rets-client#75]
Hey, just hoping for a bit of help.

I am testing out performing an initial download of a RETS database (we are not aloud to do ad hock search queries to the DB we must download and maintain an entire copy ourselves and then perform searchers from our own DB)

I call getAutoLogoutClient() and then perform the first search.query() using a RETS test server that only returns 963 records. I am also limited to pulling 100 full listings at a time. So I then loop through a bunch more search.query() incrementing  offset by 100 each time. I should of course get back 100 records each time except for the final one where I should only get 63 records however I always get 1000 records returned. 

Now if I just do a single query and set  offset: 900 I will get 63 records returned. I have tried everything I can and nothing seems to work.

Should I be calling .getAutoLogoutClient() within my loop? Or can I just call it once for the initial query and then just keep calling search.query() after that? 

If this is a stupid way to go about it im open to other suggestions. I also realize the issue is probably on the RETS server side of things and nothing to do with rets-client but just thought id ask in case anyone has seen this behavior before.

Thanks.

**Comment by zacronos** [comment]
That...  is definitely a strange problem.  The fact that you can get the correct number of records with a single query and `offset: 900` leads me to suspect a problem with your loop of some sort.

Looping with promises can be tricky, so it seems very possible there is something subtle that needs to change, rather than something big and obvious.  Generally speaking, you should be fine calling `.getAutoLogoutClient()` once, and it should keep your session open as long as you don't resolve or reject whatever promise you return within that handler.  You could try using `.login()` and `.logout()` manually instead of `.getAutoLogoutClient()`, but honestly I don't think that's the crux of the issue.

Would you mind posting the relevant portions of your code?

**Comment by esvinson** [comment]
Are you specifying the limit param as `limit` (all lower case)?

Can you enable the debug environment variable `DEBUG=rets-client:*` and show the query string that it's generating?

Which RETS feed are you seeing this with?

If all else fails, you can do a query to pull back the KeyField only (Per RETS spec there shouldn't be a limit when returning just the key field), and then chunk those values into sets of 100 and just query for those IDs.  (This is similar to how we sync stuff, as it's compatible with some of the feeds that don't support `offset`)

**Comment by GifCo** [comment]
@zacronos  yea I'm sure it is something with my loop. This is kind of embarrassing but here is my code please note I was just hacking away on this for hours last night just trying every little thing to make it work so its quite a mess.

```javascript
router.get('/', function(req, res, next) {
// GET Listings 
    rets.getAutoLogoutClient(clientSettings, function (client) {
        
        return client.search.query("Property", "Property", "(LastUpdated=2012-03-16T00:00:00)", { limit: 100, offset: 1 })
            .then((search_res)=>   {
        
            if(search_res.count !== 0){

                // required for couchDB _bulk_docs api
                let docs = { docs: search_res.results }
                //Put listings in the couchDB
                axios.post('http://admin:Burton22@127.0.0.1:5984/rets_store_test/_bulk_docs', docs).then((status) => {
                    // do some error checking
                }).catch(err => { console.log(err) });
                
                let offset_increment = 100;
                let rounds = (Math.floor(search_res.count/100));
                let counter = 0;
            
                while (counter < rounds){
                    
                    //get next batch of results
                    rets.getAutoLogoutClient(clientSettings, function (client2) {
                        return client2.search.query("Property", "Property", "(LastUpdated=2012-03-16T00:00:00)", { limit: 100, offset: offset_increment })
                            .then((next_results)=>{
                                
                                let next_docs = {docs: next_results.results};
                                   
                                axios.post('http://admin:Burton22@127.0.0.1:5984/rets_store_test/_bulk_docs', next_docs).then((status) => {     
                                }).catch(err => { console.log(err) });
                                                                
                                offset_increment = offset_increment + 100;                        
                            })
                    })

                    counter++;
                }
            }
        res.send(search_res)

        }).catch((err)=> {console.log(err) })
    });
});
```

@esvinson yea I am using limit all lower case and it seems to work fine, for initial testing I was using limits of 5, 10, 100 and no issues there.
I am using CREA rets in Canada and they are not a fan of following the RETS spec unfortunately so there could be some funny business there as well.
Im just trying to refactor into a super simplified version of the above code to make debugging a little easier. If I still cant get it Ill run the rets-client DEBUG.  

Cheers

**Comment by zacronos** [comment]
Ok yeah, the problem is definitely the way you were using a regular looping construct with something async happening inside -- basically, with this code as-is, you were firing off a bunch of requests all at once without waiting for them to finish.

That's fine (if your RETS server allows it), except that you were incrementing the offset only after your received the data -- so you were essentially asking for (probably) the first 100 results each time.

Try moving your `offset_increment = offset_increment + 100` line to the place where you do `counter++`, and I bet you'll see the problem go away.  (Also, you don't need to call `getAutoLogoutClient` within your loop, as we've already discussed.)

**Comment by zacronos** [comment]
Also, as some general advice, I'm a fan of the shotgun-logging approach to troubleshooting.  ;-)  Take a look at this snippet, I bet with these debug logging lines in place you would have been able to figure out what was happening:

```javascript
                while (counter < rounds){
                    
                    //get next batch of results
                    rets.getAutoLogoutClient(clientSettings, function (client2) {
                        console.log('@@@@@@@@@@@@@@@@@@@@ making query with offset: '+offset_increment);
                        return client2.search.query("Property", "Property", "(LastUpdated=2012-03-16T00:00:00)", { limit: 100, offset: offset_increment })
                            .then((next_results)=>{
                                console.log('==================== received query results');
                                let next_docs = {docs: next_results.results};
                                   
                                axios.post('http://admin:Burton22@127.0.0.1:5984/rets_store_test/_bulk_docs', next_docs).then((status) => {     
                                }).catch(err => { console.log(err) });
                                                                
                                offset_increment = offset_increment + 100;                        
                                console.log('-------------------- offset_increment increased to: '+offset_increment);
                            })
                    })

                    counter++;
                }
```

Having looked closer at your code, I think you will actually NEED to remove the inner `getAutoLogoutClient()` calls for this to work (in addition to moving the `offset_increment` line as I suggested before).  The problem is a very common type of bug in javascript code, where there is a closure inside a loop, and a variable updated in the loop but outside the closure is used inside the closure.

If you're not familiar with the "javascript closure loop bug" problem, I suggest reading up on it.  Here's a start: http://stackoverflow.com/questions/750486/javascript-closure-inside-loops-simple-practical-example

**Comment by GifCo** [comment]
@zacronos THANK YOU!! Moving the offset_increment outside the closure did the trick I think. I was going a bit crazy yesterday as I could see it was duplicating some of the requests so the first 200 were all fine but then 300 and 400 blocks were duplicates.

I am still trying to get the hang of promises so sorry for the noob question. I also love the shotgun-logging approach as well, before I copy/pasted for you to see almost every other line was a console.log!! lol Just thought it was cleaner not to include them.

One last issue, after removing the inner getAutoLogoutClient() I am getting some ReplyCode 20701 (NOT_LOGGED_IN) errors as it runs through the loop. It is quite sporadic though. It will usually get the first few batches of 100 records and then skip a few (due to login error) and then get the last ones. Testing it right now with my original search query that is returning 962 results, the first time I run it I get 862 records into the DB the second time i only got 682 and so on.

I'm not to worried though as this is just a test RETS server that has not been updated in some time and I have just finished a quick refactor and I dont seem to be seeing that issue with the new code. But when I took the code above and just removed getAutoLogoutClient() I was definitely seeing the issue repeatedly.

Thanks again so much for your help you saved me another massive headache, which is never fun on a Friday! :)

**Comment by esvinson** [comment]
Cleaner example using async/await instead of the promise chain.. (I haven't tested this)

It should at least show the logic you should be using.
- Single login client
- Singe search loop

```
router.get('/', function(req, res, next) {
    rets.getAutoLogoutClient(clientSettings, async (client) => {
        let total_records = 0;            
        let offset = 1;
        let limit = 100;
        do {
            let search_res = await client.search.query("Property", "Property", "(LastUpdated=2012-03-16T00:00:00)", { limit, offset });
            if (search_res.count) {
                if (total_records === 0) {
                    total_records = search_res.count;
                }
                // required for couchDB _bulk_docs api
                let docs = { docs: search_res.results }
                //Put listings in the couchDB
                try {
                    let status = await axios.post('http://127.0.0.1:5984/rets_store_test/_bulk_docs', docs);
                    // do some error checking
                } catch (err) {
                    console.log(err);
                }
                offset += limit;
            }
        } while (offset < total_records);
    })
        .catch((err)=> {console.log(err) })
        .then(() => res.send('Done'));
});
```

**Comment by GifCo** [comment]
@esvinson thanks for that! After I actually got this working I was going to ask what is the best way to go about this.
Is it your opinion that it is always better to use asnyc/await instead of just promises when you need to do looping like this?

Thanks for the advice. Much appreciated.

**Comment by zacronos** [comment]
I believe the reason you are getting sporadic `NOT_LOGGED_IN` errors is also related to your promise handling -- when a promise is returned within a `getAutoLogoutClient()` handler, the session will automatically be logged out as soon as that promise is resolved or rejected.  With your code as it is (even with the suggestions I've made so far), that first outer query you make is being allowed to resolve without waiting for your other queries to finish, and possibly without waiting for all of them to even be initiated.  That means you could get logged out before you want to be.

To fix this, you'll need to find a way to be more deliberate with your promises.  I actually haven't familiarized myself with `async`/`await` as @esvinson suggested, but that could be an easy answer.  Otherwise, you'll have to figure out how to carefully chain your promises together.

**Comment by esvinson** [comment]
@GifCo Not necessarily, but for this instance I think it's better, as you have an unknown (at the start) number of async requests you need to make, so there's not an easy way to doing a Promise.map or Promise.each type call.

**Comment by GifCo** [comment]
@zacronos Yes I think its safe to assume my promise handling could do with some improving. :) 
The way I have gotten it to work properly and consistently now still has getAutoLogoutClient() being called on every iteration of the loop. In the code below I have hard coded my counter so ignoring that for the time being does this seem ok? Or should I really try and avoid calling getAutoLogoutClient() so often?

```javascript
router.get('/', function (req, res, next) {
    
    let counter = 0;
    let offset = 0;
    
    while(counter < 10){
        
        pullListings(offset).then((results)=>{
            axios.post('http://127.0.0.1:5984/rets_store_test/_bulk_docs', {docs: results.results}).then((status) => {
            
            }).catch((err)=>{ console.log(err) });
        
        }).catch(err=>{console.log(err)})
        offset += 100;
        counter++    
    }

    res.send(200);
    
}); //end of router.get()

function pullListings( offset ) {
    let current_offset = offset === undefined || offset === 0 ? 1 : offset;

    //login to RETS
    return rets.getAutoLogoutClient(clientSettings, function (client) {
        
        return client.search.query("Property", "Property", "(LastUpdated=2012-03-16T00:00:00)", { limit: 100, offset: current_offset })

    }); //end of getAutoLogoutClient()
}
```

I guess this is what you are talking about @esvinson when you say async/await is better when you have an unknown at the start of a promise chain. 
I think Ill be spending most of my weekend reading up on async/await now! Ill let you know how it goes.

**Comment by zacronos** [comment]
What you have now looks like it would be fine for RETS servers which allow enough simultaneous logins -- using `getAutoLogoutClient()` this way means you are doing a separate login and logout for each query you want to make.  Keep in mind though that if there is a limit on simultaneous logins of e.g. 10, then you won't have any problem on the test server (since pulling <= 1000 listings in batches of 100 will never create more than 10 queries), but on a live server with > 1000 listings you could have problems.

I have seen RETS servers that only allow 1 login at a time, and this would definitely not work on those servers.  But, if your RETS server allows unlimited, then I see no real problem, just a very little lag/inefficiency since you are making unnecessary logins and logouts.

**Comment by GifCo** [comment]
@zacronos yea that makes sense. Probably safer to not have so many unnecessary logins.

Thanks again. Have a good weekend!

**Comment by esvinson** [comment]
Sticking to a single login is the best option. 

You could try a recursive approach to calling pullListings

This looks kind of ugly but should work.

```
router.get('/', function (req, res, next) {
    rets.getAutoLogoutClient(clientSettings, function (client) {
        return pullListings(client, 100, 1, sendListingsToCouchDB)
    })
        .catch((err) => {
            console.log(err);
        })
        .then((res) => {
            res.send(200);
        });
    ;
}); //end of router.get()

function sendListingsToCouchDB(results) {
    return axios.post('http://127.0.0.1:5984/rets_store_test/_bulk_docs', {docs: results.results})
        .then((status) => {
        })
        .catch((err)=>{ console.log(err) });
}

function pullListings( client, limit, offset, handler ) {
    let current_offset = offset === undefined || offset === 0 ? 1 : offset;
    return client.search.query("Property", "Property", "(LastUpdated=2012-03-16T00:00:00)", { limit: limit, offset: current_offset }).
        then((results) => {
            handler(results); // Note: this is going to be done asynchronously with no regard for failures.
            offset += limit;
            if (results.count > offset) {
                return pullListings(client, limit, offset, handler);
            }
        });
}
```

**Comment by GifCo** [comment]
Thanks for the recursive suggestion @esvinson , I've refactored and it is much cleaner and easier to read however I am seeing a pretty massive performance drop compared to just using a while loop. After executing with the loop as fast as I can tab over to couchDB there are already 961 records there. With recursion I tab over see a few hundred and have to reload/wait about 30-40 seconds before all the records show up. Would I be correct in thinking the loop is much faster because I have hard-coded the number of iterations and it just fires off request after request not needing to wait to check (results.count > offset) ?? Or should I be looking deeper into this?

Here is the code I am running...

Looping (fast)
```javascript
router.get('/', function (req, res, next) {
    
    let counter = 0;
    let offset = 1;

    while(counter < 10){
        
        pullListings(offset).then((results)=>{
            axios.post('http://admin:Burton22@127.0.0.1:5984/rets_store_test/_bulk_docs', {docs: results.results}).then((status) => {
            
            }).catch((err)=>{ console.log(err) });
        
        }).catch(err=>{console.log(err)})
        offset += 100;
        counter++    
    }
    res.send(200);
    
}); //end of router.get()

function pullListings( offset ) {
    //login to RETS  !!!! Try and remove !!!!
    return rets.getAutoLogoutClient(clientSettings, function (client) {
        
        return client.search.query("Property", "Property", "(LastUpdated=2012-03-16T00:00:00)", { limit: 100, offset: offset })

    }); //end of getAutoLogoutClient()
}
```

Recursive (slower):
```javascript
router.get('/', function (req, res, next) {

    let offset = 1;
    //login to the RETS server
    rets.getAutoLogoutClient(clientSettings, function (client) {

        return pullListings(offset, client)

    }).catch((err)=>{console.log(err)}) //end of getAutoLogoutClient

    res.send(200);

}); //end of router.get()

function pullListings(offset, client) {

    return client.search.query("Property", "Property", "(LastUpdated=2012-03-16T00:00:00)", { limit: 100, offset: offset })
        .then((results)=>{
            axios.post('http://admin:Burton22@127.0.0.1:5984/rets_store_test/_bulk_docs', { docs: results.results })
                .catch((err) => { console.log(err) });
            
            //increment offset
            offset += 100;

            if(results.count > offset){
                return pullListings(offset, client);
            }
        }).catch(err=>{console.log(err)})
}
```

**Comment by esvinson** [comment]
I'd expect it to be a bit slower as it's waiting for the query to finish before it moves on to the next, whereas the old one would just fire off a ton of queries/connections at the same time.

Also, you might want to clear the extra info out of your URLs above :-P

**Comment by GifCo** [comment]
@esvinson thanks! Its just a local dev setup but still not a good idea to leave that stuff in there!
