### ISSUE TITLE
All numeric values are converted to strings

### ISSUE THREAD

**Issue by gstreetmedia** [sbruno81/rets-client#76]
I realize that one can first create a typemap for converting the data to its correct format. But is there a reason that all numeric values are converted to Strings values by default? I'm not really familiar with CS, but I've been pouring through the code trying to find out where this happens, but have had no success so far.

**Comment by esvinson** [comment]
I'd assume this is because there's not really any way to tell the type of of the variables being returned by the RETS server unless you were to pull back the table schema first (which would slow everything down)

Example RETS query response:
```
<RETS ReplyCode="0" ReplyText="">
<COUNT Records="2117">
<DELIMITER value="09"/>
 <COLUMNS> ListingID ListPrice </COLUMNS>
 <DATA> 12345678 300000 </DATA>
 <DATA> 23456789 300000 </DATA>
 <DATA> 34567890 300000 </DATA>
 <DATA> 45678901 300000 </DATA>
 <DATA> 56789012 310000 </DATA>
 <DATA> 67890123 310000 </DATA>
 <DATA> 78901234 310000 </DATA>
 <DATA> 89012345 300000 </DATA>
 <DATA> 90123456 350000 </DATA>
 <DATA> 01234567 400000 </DATA>
</RETS>
```

Nothing in there says the type.  In the example of the last entry with a leading 0 in a number, that would be a string, but with all previous values you might have thought that value would be a number.

Example pulled from http://www.mredllc.com/rets/documents/RETS%20Developer%20Start%20Guide1.pdf

**Comment by zacronos** [comment]
The reason you're not finding it is because the code in this module doesn't convert values to strings.  The start as strings, and this module simply passes them through as-is.

This is further complicated by the fact that even a value which is known to be a number could come back as a special value which means "we have a value, but we're not going to give it to you".  So you shouldn't be assuming you get a number, even for fields which are never any non-number value on the RETS server.

Rather than having this module do the effort of figuring out what type every field should be, which would incur processing overhead, the easier (and often more performant) approach is to have this module do as little as possible.  For instance, if you are streaming the data from the RETS server to a database, sometimes you never need to convert a number value to a string in your application code -- it would just be converted back to text to be sent to the db anyway.
