### ISSUE TITLE
Inconsistant searches, getting ReplyCode 20701 (NOT_LOGGED_IN) alot

### ISSUE THREAD

**Issue by invisibled** [sbruno81/rets-client#84]
Hoping i can get some advice about searching with your library. For the record, this script does work, the issue is more often than not, i get `RETS Server reply while attempting search - ReplyCode 20701 (NOT_LOGGED_IN); ReplyText: Not Logged In` in the `getListingKeys` function.

This script gets called from a `POST` request, with a `ListingId` as the payload. It then searches all of the realtor's listings for a matching `ListingId` and returns it if it exists.

I've been searching the issues here and have seen some similar issues due to improper handling of promises, and it might be something like that?

Is there any way to explicitly check if i'm logged in? 

There must be a way to wait to be logged in and then execute all my code while still logged in... right?

Any ideas, tips etc are highly welcomed.

```
    rets.getAutoLogoutClient(crea.clientSettings, async (client => {
      crea.client = client
      console.log(crea.client);

      crea.getListingKeys()
    })).catch(crea.showError)
  },

  getListingKeys : () => {
    crea.client.search.query("Property", "Property", "(ID=*)", null)
      .then( searchData => {
        for (var dataItem = 0; dataItem < searchData.results.length; dataItem++) {
          console.log("   -------- Result " + dataItem + " --------");
          crea.outputFields(searchData.results[dataItem]);
          crea.listingKeys.push(searchData.results[dataItem].ListingKey);
        }
      }).then(crea.getProperties);
  },

  getProperties : () => {
    crea.client.search.query("Property", "Property", "(ID="+crea.listingKeys.join(',')+")", null).then( searchData => {
      for (let property of searchData.results) {
        console.log( property.ListingId, crea.requestedPropertyId );
        if (property.ListingId === crea.requestedPropertyId) {
          console.log("=========== MATCH ==========");
          crea.property = property;
          crea.outputFields(property);

          return crea.res.send(property);
        }
      }

      return crea.res.send({error:"No Property Found"});
    });
  },
```

**Comment by zacronos** [comment]
It looks to me like the main problem is that you need to be in the habit of returning promises from your functions -- for example I think the first line of `getListingKeys()` should start with `return`, and similar for the first line of `getProperties()`.

You may also need to `return crea.getListingKeys()` from inside the `getAutoLogoutClient()` closure.

Give those a try -- if you need more context for that to make sense, please let me know.

**Comment by invisibled** [comment]
damn you are right friend, i'm getting consistant responses now. I wasn't sure what should be returning so i believe thats why i left them out when i originally wrote this script.

Just curious... do you know why NOT returning like that gives an not logged in error? I would think the connection i create and store in `crea.client` would stay alive through my functions. Obviously it didn't but JW if you have any insight into that. 

I really appreciate your prompt reply even if it was just to fix my stupid mistakes :D

**Comment by zacronos** [comment]
Sure thing, I'm glad to help.

The reason you get logout errors from a missing return is because of the way the `getAutoLogoutClient()` "magic" is implemented.  Basically, it expects your handler function to return a promise, and it keeps the client logged in until that promise resolves -- and then it logs out for you.  If the promise chain isn't correctly preserved, the logout will happen before some of your code completes.

There are other functions available that don't do this auto-logout magic.  I prefer auto-logout because it ensures you never leave a client connected, and since some RETS servers restrict your number of simultaneous logins, leaving a client connected unnecessarily may mean you can't login elsewhere when you need to.  But, if you want to, you can use `rets.Client.login()` and `rets.Client.logout()` manually.  I can't remember if there are any examples of that approach.  My day job no longer involves real estate, so I'm not going to personally spend the time to create more examples and documentation, but if someone else wants to do so I'd be happen to merge a PR.

**Comment by invisibled** [comment]
ahhhh gotcha, that helps a lot thanks for that explanation! My day job is ONLY real estate now, and i've been working with this library more often so i'm really trying to understand it as much as i can, it's very helpful. Thanks!
